### PR TITLE
replace ifndef guards with pragma once

### LINKED ISSUE #243: Change to using #pragma once
As opposed to `#ifndef`-based guards around header files.

### PR DESCRIPTION
**Pull request by ianklatzco**
Closes #243.

### CODE REVIEW

**Comment by ianklatzco** [comment]
Oh, whoops. Looks like #271  does the same thing and was submitted yesterday. I checked the issues, but not the outstanding PRs when I started working on this.

**Comment by jacwil** [comment]
No worries. Feel free to create the pull request. I'm still getting myself used to the code.

**Comment by pgoodman** [comment]
@ianklatzco and @jacwil both PRs are closed. Should I re-open one of them?

**Comment by ianklatzco** [comment]
Looks like we both missed some ifndef guards. I've incorporated jacwil's changes into this PR.

**Pull request merged**
